version: '3'

networks:
  backend-network:
    driver: bridge

volumes:
  pgdata:

services:
  backend:
    container_name: mentor-backend
    image: auxxxxx/itam_mentor_service202504032057
    restart: always
    ports:
      - "8000:8000"
    environment:
      - APP_PG__HOST=postgres
      - APP_PG__USERNAME=db_main
      - APP_PG__PASSWORD=db_main
      - APP_PG__DATABASE=db_main
      - APP_PG__PORT=5432
      - APP_UVICORN__HOST=0.0.0.0
      - APP_UVICORN__PORT=8000
      - APP_UVICORN__WORKERS=1
      - APP_CORS__ALLOW_ORIGINS=["*"]
      - APP_CORS__ALLOW_CREDENTIALS=false
      - APP_CORS__ALLOW_METHODS=["*"]
      - APP_CORS__ALLOW_HEADERS=["*"]
      - DEBUG=true
    depends_on:
      - postgres
    networks:
      - backend-network

  postgres:
    container_name: mentor-postgres
    image: postgres:17.0
    restart: always
    environment:
      - POSTGRES_USER=db_main
      - POSTGRES_PASSWORD=db_main
      - POSTGRES_DB=db_main
      - PGUSER=db_main
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    networks:
      - backend-network